spring.application.name=facturacion-service
server.port=8087

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/bd_facturacion?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.jpa.hibernate.ddl-auto=none
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
spring.jpa.show-sql=true

api.base-url=${API_BASE_URL:http://localhost:8086}
api.reparacion.exists=/reparaciones/%d/exists