spring.application.name=notificacion-service
server.port=8090

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/bd_notificacion?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.jpa.hibernate.ddl-auto=none
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
spring.jpa.show-sql=true

logging.file.name=logs/notificacion-service.log
logging.pattern.console=%d{HH:mm:ss} %-5level %msg%n
logging.pattern.file=%d{HH:mm:ss} %-5level %msg%n

api.reparacion.base-url=${API_REPARACION_BASE_URL:http://localhost:8086}
api.reparacion.exists=/reparaciones/%d/exists